services:

  php:

    volumes:
      - ./backend:/var/www/html
      - ./deploy/docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
      - ./deploy/docker/php/php.dev.ini:/usr/local/etc/php/conf.d/99-dev.ini:ro
      - ./deploy/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

    environment:
      APP_ENV: local
      APP_DEBUG: "true"

      XDEBUG_MODE: debug

    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:

    stdin_open: true

    tty: true

  nginx:

    volumes:
      - ./backend:/var/www/html:ro
      - ./deploy/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:

    ports:
      - "5432:5432"

  redis:

    ports:
      - "6379:6379"