FROM node:22-alpine AS frontend

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

COPY frontend/ .

ARG VITE_API_URL=/api
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_VK_APP_ID=
ENV VITE_VK_APP_ID=$VITE_VK_APP_ID

RUN npm run build


FROM nginx:1.29-alpine

COPY deploy/docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend /app/dist /var/www/frontend

EXPOSE 80
